# API RAG QA Pipeline

This notebook builds a RAG pipeline for the PDF-derived Markdown corpus and answers the questions in `qa_set.csv`.

It is designed for a non-local/cloud notebook environment:

- Put the converted Markdown files and `qa_set.csv` in the same folder as this notebook.
- Set `CSCS_API_KEY` in the environment, or create a file named `environment` containing `CSCS_API_KEY=...`.
- The LLM answer generation uses the Swiss AI OpenAI-compatible API.

Retrieval settings used below:

- Chunk size: `250` words
- Chunk overlap: `50` words
- Cosine similarity threshold: `0.15`
- Maximum context chunks sent to the model: `6`
- Minimum fallback chunks: `3`

## 1. Install and Import Dependencies

In [1]:
# Run this cell once in a fresh notebook environment.
%pip install -q openai python-dotenv pandas scikit-learn numpy tqdm

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import csv
import json
import os
import re
import sqlite3
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm.auto import tqdm

load_dotenv(dotenv_path="environment")

WORK_DIR = Path.cwd()
QA_CSV = WORK_DIR / "qa_set.csv"
OUTPUT_CSV = WORK_DIR / "qa_set_api_rag_answers.csv"
DB_PATH = WORK_DIR / "rag_tfidf_database.sqlite"

CHUNK_WORDS = 250
OVERLAP_WORDS = 50
SIMILARITY_THRESHOLD = 0.15
MAX_CONTEXT_CHUNKS = 6
MIN_CONTEXT_CHUNKS = 3

API_BASE_URL = "https://api.swissai.svc.cscs.ch/v1"
MODEL_NAME = "moonshotai/Kimi-K2.5-SDSC"  # Strongest model listed in the API example.
# Fast alternative: "zai-org/GLM-4.7-Flash"
# Open model alternatives: "swiss-ai/Apertus-8B-Instruct-2509", "swiss-ai/Apertus-70B-Instruct-2509"

client = OpenAI(
    base_url=API_BASE_URL,
    api_key=os.getenv("CSCS_API_KEY"),
)

print("Working directory:", WORK_DIR)
print("qa_set.csv exists:", QA_CSV.exists())
print("API key configured:", bool(os.getenv("CSCS_API_KEY")))

Working directory: /home/renku/work/Durham-Hackathon-2026-w2t1
qa_set.csv exists: True
API key configured: True

## 2. Load Markdown Corpus

In [6]:
IMAGE_PATTERN = re.compile(r"!\[[^\]]*\]\([^)]+\)")
WORD_PATTERN = re.compile(r"\S+")


def clean_markdown(text: str) -> str:
    text = IMAGE_PATTERN.sub(" ", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(r"[ \t]+", " ", text)
    return text


markdown_files = sorted(
    path for path in WORK_DIR.glob("*.md")
    if path.name.lower() not in {"readme.md"}
)

if not markdown_files:
    raise FileNotFoundError(
        "No .md files found. Put the PDF-derived Markdown files in the same folder as this notebook."
    )

print(f"Found {len(markdown_files)} Markdown files:")
for path in markdown_files:
    print("-", path.name)

Found 4 Markdown files:
- Web Version _E-Government Survey 2024 11102024.md
- World_Inequality_Report_2026.md
- natural-catastrophe-and-climate-report-2023.md
- swissre_sigma-1_2024_english.md

## 3. Chunk the Corpus

In [7]:
@dataclass(frozen=True)
class Chunk:
    chunk_id: int
    source: str
    chunk_index: int
    start_word: int
    end_word: int
    text: str


def chunk_text(source: str, text: str, chunk_words: int, overlap_words: int, start_id: int) -> list[Chunk]:
    if overlap_words >= chunk_words:
        raise ValueError("Overlap must be smaller than chunk size.")

    words = WORD_PATTERN.findall(clean_markdown(text))
    if not words:
        return []

    chunks = []
    step = chunk_words - overlap_words
    for chunk_index, start in enumerate(range(0, len(words), step)):
        end = min(start + chunk_words, len(words))
        chunks.append(
            Chunk(
                chunk_id=start_id + len(chunks),
                source=source,
                chunk_index=chunk_index,
                start_word=start,
                end_word=end,
                text=" ".join(words[start:end]),
            )
        )
        if end == len(words):
            break
    return chunks


chunks: list[Chunk] = []
next_id = 1
for md_path in markdown_files:
    text = md_path.read_text(encoding="utf-8", errors="replace")
    file_chunks = chunk_text(md_path.name, text, CHUNK_WORDS, OVERLAP_WORDS, next_id)
    chunks.extend(file_chunks)
    next_id += len(file_chunks)

print(f"Created {len(chunks)} chunks.")
pd.DataFrame([c.__dict__ for c in chunks[:5]])

Created 1044 chunks.

,chunk_id,source,chunk_index,start_word,end_word,text
0,1,Web Version _E-Government Survey 2024 11102024.md,0,0,250,## **E-Government Survey 2024** Accelerating D...
1,2,Web Version _E-Government Survey 2024 11102024.md,1,200,450,‘country’ and ‘economy’ as used in this Report...
2,3,Web Version _E-Government Survey 2024 11102024.md,2,400,650,"or its senior management, or of the experts wh..."
3,4,Web Version _E-Government Survey 2024 11102024.md,3,600,850,2024 UN E-GovErNmENt SUrvEy iv PREFAcE ## **Pr...
4,5,Web Version _E-Government Survey 2024 11102024.md,4,800,1050,is crucial for comprehensive digital transform...

## 4. Build Embeddings and Save the RAG Database

In [8]:
# TF-IDF embeddings are deterministic, fast, and work in a cloud notebook without local LLM inference.
# Cosine similarity is computed over these embeddings.

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_features=80_000,
    min_df=1,
)

chunk_texts = [chunk.text for chunk in chunks]
chunk_matrix = vectorizer.fit_transform(chunk_texts)

print("Embedding matrix shape:", chunk_matrix.shape)
print("Vocabulary size:", len(vectorizer.vocabulary_))

Embedding matrix shape: (1044, 80000)
Vocabulary size: 80000

In [9]:
def save_database(db_path: Path) -> None:
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(
            """
            CREATE TABLE metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );

            CREATE TABLE chunks (
                id INTEGER PRIMARY KEY,
                source TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                start_word INTEGER NOT NULL,
                end_word INTEGER NOT NULL,
                text TEXT NOT NULL
            );

            CREATE INDEX idx_chunks_source ON chunks(source);
            """
        )
        metadata = {
            "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "chunk_words": CHUNK_WORDS,
            "overlap_words": OVERLAP_WORDS,
            "similarity_threshold": SIMILARITY_THRESHOLD,
            "max_context_chunks": MAX_CONTEXT_CHUNKS,
            "min_context_chunks": MIN_CONTEXT_CHUNKS,
            "embedding_backend": "sklearn-tfidf-word-1-2gram",
            "chunk_count": len(chunks),
            "sources": sorted({chunk.source for chunk in chunks}),
        }
        conn.execute(
            "INSERT INTO metadata(key, value) VALUES (?, ?)",
            ("index", json.dumps(metadata, indent=2)),
        )
        conn.executemany(
            """
            INSERT INTO chunks(id, source, chunk_index, start_word, end_word, text)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    chunk.chunk_id,
                    chunk.source,
                    chunk.chunk_index,
                    chunk.start_word,
                    chunk.end_word,
                    chunk.text,
                )
                for chunk in chunks
            ],
        )
        conn.commit()
    finally:
        conn.close()


save_database(DB_PATH)
print("Saved database:", DB_PATH)

Saved database: /home/renku/work/Durham-Hackathon-2026-w2t1/rag_tfidf_database.sqlite

## 5. Retrieval With Cosine Similarity Threshold

In [10]:
def retrieve_chunks(
    question: str,
    threshold: float = SIMILARITY_THRESHOLD,
    max_chunks: int = MAX_CONTEXT_CHUNKS,
    min_chunks: int = MIN_CONTEXT_CHUNKS,
) -> list[dict]:
    query_vector = vectorizer.transform([question])
    scores = cosine_similarity(query_vector, chunk_matrix).ravel()
    ranked_indices = np.argsort(scores)[::-1]

    selected = [
        {
            "chunk_id": chunks[i].chunk_id,
            "source": chunks[i].source,
            "chunk_index": chunks[i].chunk_index,
            "score": float(scores[i]),
            "text": chunks[i].text,
        }
        for i in ranked_indices
        if scores[i] >= threshold
    ][:max_chunks]

    # Fallback: if the threshold is too strict for a short/narrow question,
    # still provide the best few chunks so the model can answer or say not found.
    if len(selected) < min_chunks:
        fallback = [
            {
                "chunk_id": chunks[i].chunk_id,
                "source": chunks[i].source,
                "chunk_index": chunks[i].chunk_index,
                "score": float(scores[i]),
                "text": chunks[i].text,
            }
            for i in ranked_indices[:min_chunks]
        ]
        seen = {item["chunk_id"] for item in selected}
        selected.extend(item for item in fallback if item["chunk_id"] not in seen)

    return selected[:max_chunks]


sample_question = "How much higher are the 2023 insured losses than the previous 10 year average?"
sample_chunks = retrieve_chunks(sample_question)
[(c["score"], c["source"], c["chunk_index"]) for c in sample_chunks]

[(0.30275251596238184, 'swissre_sigma-1_2024_english.md', 16),
 (0.2613026064759836, 'swissre_sigma-1_2024_english.md', 12),
 (0.21706114729252715, 'swissre_sigma-1_2024_english.md', 21),
 (0.1919479831370779, 'swissre_sigma-1_2024_english.md', 4),
 (0.18614294405272064, 'swissre_sigma-1_2024_english.md', 14),
 (0.17711066061379332, 'swissre_sigma-1_2024_english.md', 1)]

## 6. API Answer Generation

In [13]:
SYSTEM_PROMPT = """You are a careful RAG question-answering assistant.
Use only the supplied context.
Answer concisely, preferably in one or two sentences.
If the context does not contain the answer, write exactly: Not found in the retrieved context.
When relevant, include exact years, percentages, counts, names, or figure numbers.
Do not invent citations. Do not mention chunks unless asked.
"""


def format_context(retrieved: list[dict], max_chars_per_chunk: int = 1600) -> str:
    parts = []
    for i, chunk in enumerate(retrieved, start=1):
        text = chunk["text"][:max_chars_per_chunk]
        parts.append(
            f"[Context {i}] source={chunk['source']} chunk={chunk['chunk_index']} cosine={chunk['score']:.3f}\n{text}"
        )
    return "\n\n".join(parts)


def answer_question(question: str, model: str = MODEL_NAME) -> tuple[str, list[dict]]:
    retrieved = retrieve_chunks(question)
    context = format_context(retrieved)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"Context:\n{context}\n\nQuestion: {question}\n\nAnswer:",
            },
        ],
        temperature=0.0,
        max_tokens=180,
    )
    return extract_chat_message_text(response.choices[0].message), retrieved

In [15]:
def extract_chat_message_text(message) -> str:
    content = getattr(message, "content", None)
    if isinstance(content, str) and content.strip():
        return content.strip()

    data = message.model_dump() if hasattr(message, "model_dump") else {}
    for key in ("reasoning_content", "reasoning", "output_text", "refusal"):
        value = data.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    return "Not found in the retrieved context."

In [16]:
# Single-question test.
# This cell requires CSCS_API_KEY to be configured.

if not os.getenv("CSCS_API_KEY"):
    print("Set CSCS_API_KEY before running API calls.")
else:
    answer, evidence = answer_question(sample_question)
    print("Question:", sample_question)
    print("Answer:", answer)
    print("Evidence:")
    for item in evidence:
        print(f"- {item['source']}#{item['chunk_index']} cosine={item['score']:.3f}")

Question: How much higher are the 2023 insured losses than the previous 10 year average?
Answer: Not found in the retrieved context.
Evidence:
- swissre_sigma-1_2024_english.md#16 cosine=0.303
- swissre_sigma-1_2024_english.md#12 cosine=0.261
- swissre_sigma-1_2024_english.md#21 cosine=0.217
- swissre_sigma-1_2024_english.md#4 cosine=0.192
- swissre_sigma-1_2024_english.md#14 cosine=0.186
- swissre_sigma-1_2024_english.md#1 cosine=0.177

## 7. Load QA CSV

In [17]:
def read_qa_set(path: Path) -> pd.DataFrame:
    # qa_set.csv uses semicolons: question;answer
    df = pd.read_csv(path, sep=";", keep_default_na=False)
    if "question" not in df.columns:
        raise ValueError("qa_set.csv must contain a 'question' column.")
    if "answer" not in df.columns:
        df["answer"] = ""
    df["question"] = df["question"].astype(str).str.strip()
    df["answer"] = df["answer"].astype(str).str.strip()
    return df[df["question"] != ""].reset_index(drop=True)


qa_df = read_qa_set(QA_CSV)
print("Questions:", len(qa_df))
print("Existing answers:", int((qa_df["answer"] != "").sum()))
qa_df.head()

Questions: 40
Existing answers: 5

,question,answer
0,What year where there most casualties from man...,"2002. In that year more than 10,000 casualties..."
1,In what year did the quantity of man-made disa...,Man-made disasters peaked in 2005
2,Between 1970 and 2023 what year in the data sh...,2023. There were 218 instances of natural cat...
3,What year between 1994 and 2023 had the most h...,2011 with 6.
4,How much higher are the 2023 insured losses th...,They are higher by 21%.

## 8. Answer All Questions

In [18]:
def answer_qa_dataframe(
    df: pd.DataFrame,
    preserve_existing: bool = True,
    sleep_seconds: float = 0.2,
) -> pd.DataFrame:
    rows = []
    for _, row in tqdm(df.iterrows(), total=len(df)):
        question = row["question"]
        existing_answer = row["answer"]

        retrieved = retrieve_chunks(question)
        if preserve_existing and existing_answer:
            answer = existing_answer
        else:
            answer, retrieved = answer_question(question)
            time.sleep(sleep_seconds)

        rows.append(
            {
                "question": question,
                "answer": answer,
                "retrieved_sources": " | ".join(
                    f"{item['source']}#{item['chunk_index']} ({item['score']:.3f})"
                    for item in retrieved
                ),
                "retrieved_chunk_ids": ",".join(str(item["chunk_id"]) for item in retrieved),
            }
        )
    return pd.DataFrame(rows)


if not os.getenv("CSCS_API_KEY"):
    print("Set CSCS_API_KEY before answering the full QA set.")
else:
    results_df = answer_qa_dataframe(qa_df, preserve_existing=True)
    results_df.to_csv(OUTPUT_CSV, sep=";", index=False)
    print("Wrote:", OUTPUT_CSV)
    display(results_df.head())

100%|██████████| 40/40 [03:44<00:00,  5.61s/it]

Wrote: /home/renku/work/Durham-Hackathon-2026-w2t1/qa_set_api_rag_answers.csv

,question,answer,retrieved_sources,retrieved_chunk_ids
0,What year where there most casualties from man...,"2002. In that year more than 10,000 casualties...",swissre_sigma-1_2024_english.md#79 (0.201) | s...,"1039,1032,1041"
1,In what year did the quantity of man-made disa...,Man-made disasters peaked in 2005,swissre_sigma-1_2024_english.md#72 (0.227) | s...,"1032,1033,1039"
2,Between 1970 and 2023 what year in the data sh...,2023. There were 218 instances of natural cat...,swissre_sigma-1_2024_english.md#72 (0.218) | s...,"1032,1033,981"
3,What year between 1994 and 2023 had the most h...,2011 with 6.,swissre_sigma-1_2024_english.md#23 (0.316) | s...,"983,982,981"
4,How much higher are the 2023 insured losses th...,They are higher by 21%.,swissre_sigma-1_2024_english.md#16 (0.303) | s...,"976,972,981,964,974,961"

In [22]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

display(results_df)

,question,answer,retrieved_sources,retrieved_chunk_ids
0,What year where there most casualties from man-made disasters in the recorded data?,"2002. In that year more than 10,000 casualties are ascribed to man-made catastrophes.",swissre_sigma-1_2024_english.md#79 (0.201) | swissre_sigma-1_2024_english.md#72 (0.162) | swissre_sigma-1_2024_english.md#81 (0.123),"1039,1032,1041"
1,In what year did the quantity of man-made disasters peak in the recorded data between 1970 and 2023?,Man-made disasters peaked in 2005,swissre_sigma-1_2024_english.md#72 (0.227) | swissre_sigma-1_2024_english.md#73 (0.178) | swissre_sigma-1_2024_english.md#79 (0.150),"1032,1033,1039"
2,Between 1970 and 2023 what year in the data shows the largest number of natural catastrophes?,2023. There were 218 instances of natural catastrophes.,swissre_sigma-1_2024_english.md#72 (0.218) | swissre_sigma-1_2024_english.md#73 (0.146) | swissre_sigma-1_2024_english.md#21 (0.144),"1032,1033,981"
3,What year between 1994 and 2023 had the most high severity ($5 billion in damages or more) natural catastrophes?,2011 with 6.,swissre_sigma-1_2024_english.md#23 (0.316) | swissre_sigma-1_2024_english.md#22 (0.270) | swissre_sigma-1_2024_english.md#21 (0.255),"983,982,981"
4,How much higher are the 2023 insured losses than the previous 10 year average?,They are higher by 21%.,swissre_sigma-1_2024_english.md#16 (0.303) | swissre_sigma-1_2024_english.md#12 (0.261) | swissre_sigma-1_2024_english.md#21 (0.217) | swissre_sigma-1_2024_english.md#4 (0.192) | swissre_sigma-1_2024_english.md#14 (0.186) | swissre_sigma-1_2024_english.md#1 (0.177),"976,972,981,964,974,961"
5,"Which figure shows the trend in insured losses over data from 1994 to 2023? In this figure, what is the highest insured loss year on record?",Not found in the retrieved context.,swissre_sigma-1_2024_english.md#20 (0.197) | swissre_sigma-1_2024_english.md#33 (0.194) | natural-catastrophe-and-climate-report-2023.md#25 (0.188) | swissre_sigma-1_2024_english.md#27 (0.183) | swissre_sigma-1_2024_english.md#7 (0.179) | swissre_sigma-1_2024_english.md#19 (0.178),"980,993,843,987,967,979"
6,"Before 2023, what was the highest year on record for European Severe Convective Storm losses?",Not found in the retrieved context.,natural-catastrophe-and-climate-report-2023.md#18 (0.185) | swissre_sigma-1_2024_english.md#77 (0.182) | natural-catastrophe-and-climate-report-2023.md#79 (0.181) | natural-catastrophe-and-climate-report-2023.md#22 (0.158) | swissre_sigma-1_2024_english.md#2 (0.156) | swissre_sigma-1_2024_english.md#30 (0.156),"836,1037,897,840,962,990"
7,What regions does the Swiss Re report on natural catastrophes split the US into for severe convective storm risk?,Not found in the retrieved context.,natural-catastrophe-and-climate-report-2023.md#18 (0.182) | natural-catastrophe-and-climate-report-2023.md#22 (0.170) | swissre_sigma-1_2024_english.md#77 (0.153),"836,840,1037"
8,What is the highest Benefit to Cost ratio building code element described in the Swiss Re report on natural catastrophes?,Not found in the retrieved context.,swissre_sigma-1_2024_english.md#64 (0.258) | swissre_sigma-1_2024_english.md#65 (0.122) | swissre_sigma-1_2024_english.md#79 (0.095),"1024,1025,1039"
9,"According to the Swiss Re Institute report on natural catastrophes, 2017 was a standout year in terms of insured loss damages. What were the names of the weather events which contributed most to this figure?",Not found in the retrieved context.,swissre_sigma-1_2024_english.md#20 (0.211) | swissre_sigma-1_2024_english.md#26 (0.200) | swissre_sigma-1_2024_english.md#19 (0.184) | natural-catastrophe-and-climate-report-2023.md#22 (0.166) | swissre_sigma-1_2024_english.md#11 (0.165) | swissre_sigma-1_2024_english.md#24 (0.161),"980,986,979,840,971,984"
10,"Given how the Swiss Re Institute classifies primary and secondary perils, to which category can we attribute more losses in 2023? How is insurance claim tracking characterized in this category?",Not found in the retrieved context.,swissre_sigma-1_2024_english.md#74 (0.252) | swissre_sigma-1_2024_english.md#79 (0.228) | swissre_sigma-1_2024_english.md#80 (0.174) | swissre_sigma-1_2024_english.md#34 (0.151),"1034,1039,1040,994"
11,"In historical data from the Swiss Re Institute, which geographical grouping of countries has the smallest proportion of insured losses to uninsured losses between 2014 and 2023?",Not found in the retrieved context.,swissre_sigma-1_2024_english.md#75 (0.243) | swissre_sigma-1_2024_english.md#77 (0.219) | swissre_sigma-1_2024_english.md#76 (0.216) | swissre_sigma-1_2024_english.md#78 (0.212) | swissre_sigma-1_2024_english.md#1 (0.209) | swissre_sigma-1_2024_english.md#33 (0.206),"1035,1037,1036,1038,961,993"
12,What is the lower bound of dead or missing which have to be reported in connection to a natural catastrophe in order for the Swiss Re data to report it in their statistics?,Not found in the retrieved context.,natural-catastrophe-and-climate-report-2023.md#0 (0.128) | swissre_sigma-1_2024_english.md#82 (0.113) | swissre_sigma-1_2024_english.md#13 (0.113),"818,1042,973"
13,"Excluding the overall UN average, which group of nations have more than 100 mobile broadband subscriptions per 100 residents in 2024?",Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#189 (0.338) | Web Version _E-Government Survey 2024 11102024.md#190 (0.232) | Web Version _E-Government Survey 2024 11102024.md#191 (0.203),"190,191,192"
14,"According to survey data, which feature of government web-portals experienced the largest between 2022 and 2024?",Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#186 (0.131) | Web Version _E-Government Survey 2024 11102024.md#187 (0.117) | Web Version _E-Government Survey 2024 11102024.md#20 (0.111),"187,188,21"
15,When were the simplified four stages of E-government adoption published? Which revision of the EGDI is this related to?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#43 (0.116) | Web Version _E-Government Survey 2024 11102024.md#252 (0.068) | Web Version _E-Government Survey 2024 11102024.md#196 (0.067),"44,253,197"
16,Between what years was the EGDI revision 3.0 acive?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#196 (0.120) | Web Version _E-Government Survey 2024 11102024.md#440 (0.115) | Web Version _E-Government Survey 2024 11102024.md#221 (0.107),"197,441,222"
17,"Given when academic articles using the term started being published, when were the terms E-government development index and Online services index introduced?",Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#50 (0.357) | Web Version _E-Government Survey 2024 11102024.md#51 (0.177) | Web Version _E-Government Survey 2024 11102024.md#41 (0.169) | Web Version _E-Government Survey 2024 11102024.md#42 (0.158),"51,52,42,43"
18,"Of the questions highlighted from the Member States Questionnaire in a chart, is there a discontinuity in the numbering of the questions featured? If so, which numbers are missing?",Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#97 (0.115) | Web Version _E-Government Survey 2024 11102024.md#409 (0.086) | Web Version _E-Government Survey 2024 11102024.md#115 (0.081),"98,410,116"
19,What was the percentage increase over all the 193 UN member states in EGDI scores between 2022 and 2024?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#16 (0.184) | Web Version _E-Government Survey 2024 11102024.md#124 (0.174) | Web Version _E-Government Survey 2024 11102024.md#190 (0.172) | Web Version _E-Government Survey 2024 11102024.md#18 (0.170) | Web Version _E-Government Survey 2024 11102024.md#17 (0.169) | Web Version _E-Government Survey 2024 11102024.md#163 (0.164),"17,125,191,19,18,164"
20,Of the countries with very high OSI levels and high EGDI divergence what is the one with the lowest Telecommunications Infrasructure Index?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#143 (0.363) | Web Version _E-Government Survey 2024 11102024.md#144 (0.293) | Web Version _E-Government Survey 2024 11102024.md#142 (0.252) | Web Version _E-Government Survey 2024 11102024.md#145 (0.235) | Web Version _E-Government Survey 2024 11102024.md#14 (0.232) | Web Version _E-Government Survey 2024 11102024.md#127 (0.217),"144,145,143,146,15,128"
21,What grouping of nations has the closest OSI subindex average to the overall UN 193 average?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#11 (0.141) | Web Version _E-Government Survey 2024 11102024.md#154 (0.134) | Web Version _E-Government Survey 2024 11102024.md#205 (0.113),"12,155,206"
22,Why did the average number of provided online services increase while the percentage stayed the same between 2022 and 2024? How many services were assessed in each of the 2 years?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#176 (0.341) | Web Version _E-Government Survey 2024 11102024.md#177 (0.306) | Web Version _E-Government Survey 2024 11102024.md#230 (0.263) | Web Version _E-Government Survey 2024 11102024.md#17 (0.209) | Web Version _E-Government Survey 2024 11102024.md#173 (0.204) | Web Version _E-Government Survey 2024 11102024.md#229 (0.179),"177,178,231,18,174,230"
23,What percentage of european countries support filing income tax online?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#176 (0.149) | Web Version _E-Government Survey 2024 11102024.md#17 (0.130) | Web Version _E-Government Survey 2024 11102024.md#230 (0.130),"177,18,231"
24,In what percentage of countries in Oceania is one able to apply for a death certificate through a fully digitized process?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#214 (0.195) | Web Version _E-Government Survey 2024 11102024.md#180 (0.192) | Web Version _E-Government Survey 2024 11102024.md#174 (0.191) | Web Version _E-Government Survey 2024 11102024.md#17 (0.165),"215,181,175,18"
25,What region of the world contains the countries that enable fully digitized vehicle regitration? What is the percentage of countries in this region that support this?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#17 (0.200) | Web Version _E-Government Survey 2024 11102024.md#18 (0.172) | Web Version _E-Government Survey 2024 11102024.md#212 (0.152),"18,19,213"
26,In what percentage of countries in the Americas is one able to apply for disability compensation in at least a partially online manner?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#214 (0.232) | Web Version _E-Government Survey 2024 11102024.md#180 (0.230) | Web Version _E-Government Survey 2024 11102024.md#17 (0.199) | Web Version _E-Government Survey 2024 11102024.md#174 (0.181) | Web Version _E-Government Survey 2024 11102024.md#18 (0.174),"215,181,18,175,19"
27,What number of countries in Africa support digital invoicing? What is the percentage increase in that figure since 2022?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#181 (0.258) | Web Version _E-Government Survey 2024 11102024.md#198 (0.152) | Web Version _E-Government Survey 2024 11102024.md#17 (0.151) | Web Version _E-Government Survey 2024 11102024.md#182 (0.150),"182,199,18,183"
28,"What number of countries in Europe offer an E-procurement platform? Not percentage, number of countries.",Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#198 (0.270) | Web Version _E-Government Survey 2024 11102024.md#181 (0.262) | Web Version _E-Government Survey 2024 11102024.md#182 (0.210) | Web Version _E-Government Survey 2024 11102024.md#375 (0.179) | Web Version _E-Government Survey 2024 11102024.md#225 (0.171),"199,182,183,376,226"
29,What fully digital service for individuals in vulnerable situations experienced the largest percentge decline between 2022 and 2024?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#18 (0.147) | Web Version _E-Government Survey 2024 11102024.md#184 (0.146) | Web Version _E-Government Survey 2024 11102024.md#232 (0.123),"19,185,233"
30,What service for individuals in vulnerable situations has no fully digitized component in Oceania?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#212 (0.181) | Web Version _E-Government Survey 2024 11102024.md#184 (0.168) | Web Version _E-Government Survey 2024 11102024.md#183 (0.134),"213,185,184"
31,What proportion of countries offer judiciary services in a way that is accessible on mobile or through an app?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#185 (0.128) | Web Version _E-Government Survey 2024 11102024.md#97 (0.111) | Web Version _E-Government Survey 2024 11102024.md#232 (0.106),"186,98,233"
32,What landlocked countries have moved from high to very high E-government development index in the survey period?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#129 (0.283) | Web Version _E-Government Survey 2024 11102024.md#221 (0.189) | Web Version _E-Government Survey 2024 11102024.md#234 (0.151),"130,222,235"
33,What small island nation moved from the middle to the high EGDI group in the last survey period?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#129 (0.277) | Web Version _E-Government Survey 2024 11102024.md#197 (0.261) | Web Version _E-Government Survey 2024 11102024.md#196 (0.225) | Web Version _E-Government Survey 2024 11102024.md#246 (0.225) | Web Version _E-Government Survey 2024 11102024.md#218 (0.190) | Web Version _E-Government Survey 2024 11102024.md#221 (0.172),"130,198,197,247,219,222"
34,How has Japan named their initiative for removing bureaucratic inefficiencies and improving their digital government tools? What is the project's initial budget?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#294 (0.136) | Web Version _E-Government Survey 2024 11102024.md#116 (0.090) | Web Version _E-Government Survey 2024 11102024.md#336 (0.089),"295,117,337"
35,What two departments of the UK govenrment have been merged in the effort to enhance their digital transformation?,"The Government Digital Service (GDS) and the Department for Science, Innovation, and Technology (DSIT) have been merged,",Web Version _E-Government Survey 2024 11102024.md#322 (0.195) | Web Version _E-Government Survey 2024 11102024.md#321 (0.138) | Web Version _E-Government Survey 2024 11102024.md#257 (0.127),"323,322,258"
36,What country grouping appears to have the most drastic difference between EGDI levels of it's constituents?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#243 (0.192) | Web Version _E-Government Survey 2024 11102024.md#12 (0.160) | Web Version _E-Government Survey 2024 11102024.md#142 (0.133),"244,13,143"
37,What is the change in percentage of cities providing information on procurement between 2022 and 2024?,Not found in the retrieved context.,Web Version _E-Government Survey 2024 11102024.md#375 (0.265) | Web Version _E-Government Survey 2024 11102024.md#17 (0.244) | Web Version _E-Government Survey 2024 11102024.md#18 (0.219) | Web Version _E-Government Survey 2024 11102024.md#181 (0.178) | Web Version _E-Government Survey 2024 11102024.md#190 (0.168) | Web Version _E-Government Survey 2024 11102024.md#182 (0.152),"376,18,19,182,191,183"
38,"In the year before the two investment segments equalized, what was the amount invested in energy transition power generation vs fossil fuel power generation?",Not found in the retrieved context.,World_Inequality_Report_2026.md#236 (0.263) | natural-catastrophe-and-climate-report-2023.md#12 (0.185) | natural-catastrophe-and-climate-report-2023.md#11 (0.124),"680,830,829"
39,How many of the top 10 costliest environmental disasters of 2023 occurred in Latin America? Which country faced the msot expensive one?,Not found in the retrieved context.,natural-catastrophe-and-climate-report-2023.md#124 (0.130) | swissre_sigma-1_2024_english.md#5 (0.104) | World_Inequality_Report_2026.md#166 (0.100),"942,965,610"

In [32]:
TEAM_NAME = "Matterhorn"

In [33]:
import requests

BASE_URL = "http://durham-leaderboard-runai-innovation-klemen.inference.compute.datascience.ch"
leaderboard_endpoint = f"{BASE_URL}/api/v1/leaderboard"
submit_endpoint = f"{BASE_URL}/api/v1/submit"


def get_leaderboard() -> pd.DataFrame:
    leaderboard = requests.get(leaderboard_endpoint).json()
    return pd.DataFrame(leaderboard["entries"])


def submit(df: pd.DataFrame, user: str, token: str) -> pd.Series:
    if user == "your_team_name" or user == "":
        raise ValueError("Please set your team name in the 'TEAM_NAME' variable.")
    predictions = df[["question", "answer"]].to_dict(orient="records")
    submission = {"predictions": predictions}
    response = requests.post(submit_endpoint, json=submission, auth=(user, token))
    if (response.status_code // 100) != 2:
        response.raise_for_status()
    print(response.json())
    return pd.Series(response.json())

In [34]:
submit(results_df, user=TEAM_NAME, token="cant_be_empty")

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [ ]:
get_leaderboard()

## 9. Optional: Regenerate Existing Answers Too

In [ ]:
# Uncomment to regenerate every row, including rows that already had answers.
#
# results_all_regenerated = answer_qa_dataframe(qa_df, preserve_existing=False)
# results_all_regenerated.to_csv(WORK_DIR / "qa_set_api_rag_answers_regenerated.csv", sep=";", index=False)
# display(results_all_regenerated.head())

## 10. Inspect Low-Retrieval Questions

In [21]:
# This helps tune SIMILARITY_THRESHOLD and MAX_CONTEXT_CHUNKS.
# If many top scores are below 0.15, lower SIMILARITY_THRESHOLD to 0.12.
# If answers need more context, raise MAX_CONTEXT_CHUNKS to 8.

diagnostics = []
for question in qa_df["question"]:
    retrieved = retrieve_chunks(question)
    diagnostics.append(
        {
            "question": question,
            "top_score": retrieved[0]["score"] if retrieved else 0.0,
            "num_chunks_selected": len(retrieved),
            "top_source": retrieved[0]["source"] if retrieved else "",
            "top_chunk": retrieved[0]["chunk_index"] if retrieved else "",
        }
    )

diag_df = pd.DataFrame(diagnostics).sort_values("top_score")
display(diag_df.head(10))

,question,top_score,num_chunks_selected,top_source,top_chunk
18,Of the questions highlighted from the Member S...,0.114576,3,Web Version _E-Government Survey 2024 11102024.md,97
15,When were the simplified four stages of E-gove...,0.116146,3,Web Version _E-Government Survey 2024 11102024.md,43
16,Between what years was the EGDI revision 3.0 a...,0.119716,3,Web Version _E-Government Survey 2024 11102024.md,196
12,What is the lower bound of dead or missing whi...,0.127681,3,natural-catastrophe-and-climate-report-2023.md,0
31,What proportion of countries offer judiciary s...,0.127787,3,Web Version _E-Government Survey 2024 11102024.md,185
39,How many of the top 10 costliest environmental...,0.129976,3,natural-catastrophe-and-climate-report-2023.md,124
14,"According to survey data, which feature of gov...",0.130564,3,Web Version _E-Government Survey 2024 11102024.md,186
34,How has Japan named their initiative for remov...,0.135521,3,Web Version _E-Government Survey 2024 11102024.md,294
21,What grouping of nations has the closest OSI s...,0.141454,3,Web Version _E-Government Survey 2024 11102024.md,11
29,What fully digital service for individuals in ...,0.147097,3,Web Version _E-Government Survey 2024 11102024.md,18